
// Auto-generated by flue (target: cloudflare)
import { env } from 'cloudflare:workers';
import { Agent, getAgentByName } from 'agents';
import {
  Bash,
  InMemoryFs,
  admitDetachedWorkflow,
  assertWorkflowDefinition,
  createFlueContext,
  createSqlRunStore,
  CLOUDFLARE_AGENT_INTERNAL_DISPATCH_PATH,
  createCloudflareAgentRuntime,
  createSqlConversationStores,
  SqliteEventStreamStore,
  bashFactoryToSessionEnv,
  resolveModel,
  handleWorkflowRequest,
  handleRunRouteRequest,
  handleStreamRead,
  handleStreamHead,
  failRecoveredRun,
  generateWorkflowRunId,
  configureFlueRuntime,
  createDefaultFlueApp,
  hasRegisteredProvider,
  installDevLifecycleLogger,
} from '@flue/runtime/internal';
import {
  runWithCloudflareContext,
  getCloudflareAIBindingApiProvider,
  FlueRegistry,
  createCloudflareRunIndex,
  createCloudflareRunStore,
  resolveCloudflareExtension,
} from '@flue/runtime/cloudflare/internal';
import { registerApiProvider, registerProvider } from '@flue/runtime';


import * as workflow_continue_market_intelligence_scan_0 from "/Users/mac/Codemine-Mac/Work/Emma/publication/agent/.flue/workflows/continue-market-intelligence-scan.ts";
import * as workflow_market_intelligence_scan_1 from "/Users/mac/Codemine-Mac/Work/Emma/publication/agent/.flue/workflows/market-intelligence-scan.ts";
import * as workflow_research_discovery_decision_2 from "/Users/mac/Codemine-Mac/Work/Emma/publication/agent/.flue/workflows/research-discovery-decision.ts";
import * as workflow_research_discovery_finalization_3 from "/Users/mac/Codemine-Mac/Work/Emma/publication/agent/.flue/workflows/research-discovery-finalization.ts";
import * as workflow_research_discovery_provider_action_4 from "/Users/mac/Codemine-Mac/Work/Emma/publication/agent/.flue/workflows/research-discovery-provider-action.ts";
import * as workflow_translate_5 from "/Users/mac/Codemine-Mac/Work/Emma/publication/agent/.flue/workflows/translate.ts";





// ─── Internal provider registrations ────────────────────────────────────────
// User `app.ts` imports are hoisted above this body, so a user-supplied
// `registerProvider('cloudflare', ...)` runs first; the guard below
// preserves it. The runtime routes registrations without an explicit
// `gateway` through Cloudflare's default AI Gateway.

registerApiProvider(getCloudflareAIBindingApiProvider());

if (!hasRegisteredProvider('cloudflare')) {
  registerProvider('cloudflare', {
    api: 'cloudflare-ai-binding',
    binding: env.AI,
  });
}

// ─── Config ─────────────────────────────────────────────────────────────────


function normalizeBuiltModules(agentModules, workflowModules, channelModules = {}) {
  const agents = [];
  const workflows = [];
  const channelHandlers = {};
  for (const [name, mod] of Object.entries(agentModules)) {
    if (!mod.default || mod.default.__flueAgentDefinition !== true || typeof mod.default.initialize !== 'function') throw new Error('[flue] Agent "' + name + '" must default-export defineAgent(...).');
    if (mod.route !== undefined && typeof mod.route !== 'function') throw new Error('[flue] Agent "' + name + '" route export must be a callable Hono middleware value.');
    if (mod.attachments !== undefined && typeof mod.attachments !== 'function') throw new Error('[flue] Agent "' + name + '" attachments export must be a callable Hono middleware value.');
    if (mod.description !== undefined && (typeof mod.description !== 'string' || mod.description.trim().length === 0)) throw new Error('[flue] Agent "' + name + '" description export must be a non-empty string.');
    const previous = agents.find((agent) => agent.definition === mod.default);
    if (previous) throw new Error('[flue] Agents "' + previous.name + '" and "' + name + '" default-export the same agent definition value. Use distinct defineAgent(...) values for dispatchable agent modules.');
    const agent = { name, definition: mod.default };
    if (mod.description !== undefined) agent.description = mod.description;
    if (typeof mod.route === 'function') agent.route = mod.route;
    if (typeof mod.attachments === 'function') agent.attachments = mod.attachments;
    agents.push(agent);
  }

  for (const [name, mod] of Object.entries(workflowModules)) {
    assertWorkflowDefinition(mod.default, name);
    if (mod.route !== undefined && typeof mod.route !== 'function') throw new Error('[flue] Workflow "' + name + '" route export must be a callable Hono middleware value.');
    if (mod.runs !== undefined && typeof mod.runs !== 'function') throw new Error('[flue] Workflow "' + name + '" runs export must be a callable Hono middleware value.');
    const previous = workflows.find((workflow) => workflow.definition === mod.default);
    if (previous) throw new Error('[flue] Workflows "' + previous.name + '" and "' + name + '" default-export the same workflow definition value. Use distinct defineWorkflow(...) values for workflow modules.');
    const workflow = { name, definition: mod.default };
    if (typeof mod.route === 'function') workflow.route = mod.route;
    if (typeof mod.runs === 'function') workflow.runs = mod.runs;
    workflows.push(workflow);
  }

  for (const [name, mod] of Object.entries(channelModules)) {
    const channel = mod.channel;
    if (!channel || typeof channel !== 'object' || Array.isArray(channel)) throw new Error('[flue] Channel "' + name + '" must export a created channel as the named "channel" binding.');
    if (!Array.isArray(channel.routes) || channel.routes.length === 0) throw new Error('[flue] Channel "' + name + '" must declare at least one route.');
    const routes = {};
    for (const route of channel.routes) {
      if (!route || typeof route !== 'object' || Array.isArray(route)) throw new Error('[flue] Channel "' + name + '" contains an invalid route declaration.');
      if (typeof route.method !== 'string' || !/^[A-Z]+$/.test(route.method)) throw new Error('[flue] Channel "' + name + '" route method must contain only uppercase ASCII letters.');
      if (typeof route.path !== 'string' || route.path.length < 2 || !route.path.startsWith('/') || route.path.startsWith('//') || route.path.includes('?') || route.path.includes('#')) throw new Error('[flue] Channel "' + name + '" route path must be a non-empty absolute suffix without a query or fragment.');
      const segments = route.path.split('/');
      if (segments.some((segment) => segment === '.' || segment === '..')) throw new Error('[flue] Channel "' + name + '" route path must remain beneath its channel namespace.');
      if (typeof route.handler !== 'function') throw new Error('[flue] Channel "' + name + '" route handler must be callable.');
      const key = route.method + ' ' + route.path;
      if (routes[key] !== undefined) throw new Error('[flue] Channel "' + name + '" declares duplicate route "' + key + '".');
      routes[key] = route.handler;
    }
    channelHandlers[name] = routes;
  }

  return { agents, workflows, channelHandlers };
}


const agentModules = {

};
const workflowModules = {
  "continue-market-intelligence-scan": workflow_continue_market_intelligence_scan_0,
  "market-intelligence-scan": workflow_market_intelligence_scan_1,
  "research-discovery-decision": workflow_research_discovery_decision_2,
  "research-discovery-finalization": workflow_research_discovery_finalization_3,
  "research-discovery-provider-action": workflow_research_discovery_provider_action_4,
  "translate": workflow_translate_5,
};
const channelModules = {

};
const { agents, workflows, channelHandlers } = normalizeBuiltModules(agentModules, workflowModules, channelModules);
const agentIdentities = {

};
const workflowIdentities = {
  "continue-market-intelligence-scan": { bindingName: "FLUE_CONTINUE_MARKET_INTELLIGENCE_SCAN_WORKFLOW", className: "FlueContinueMarketIntelligenceScanWorkflow" },
  "market-intelligence-scan": { bindingName: "FLUE_MARKET_INTELLIGENCE_SCAN_WORKFLOW", className: "FlueMarketIntelligenceScanWorkflow" },
  "research-discovery-decision": { bindingName: "FLUE_RESEARCH_DISCOVERY_DECISION_WORKFLOW", className: "FlueResearchDiscoveryDecisionWorkflow" },
  "research-discovery-finalization": { bindingName: "FLUE_RESEARCH_DISCOVERY_FINALIZATION_WORKFLOW", className: "FlueResearchDiscoveryFinalizationWorkflow" },
  "research-discovery-provider-action": { bindingName: "FLUE_RESEARCH_DISCOVERY_PROVIDER_ACTION_WORKFLOW", className: "FlueResearchDiscoveryProviderActionWorkflow" },
  "translate": { bindingName: "FLUE_TRANSLATE_WORKFLOW", className: "FlueTranslateWorkflow" },
};

const userCloudflare = {};
const reservedCloudflareExportNames = new Set(["FlueContinueMarketIntelligenceScanWorkflow","FlueMarketIntelligenceScanWorkflow","FlueResearchDiscoveryDecisionWorkflow","FlueResearchDiscoveryFinalizationWorkflow","FlueResearchDiscoveryProviderActionWorkflow","FlueTranslateWorkflow","FlueRegistry"]);
for (const name of Object.keys(userCloudflare)) {
  if (name === 'default') continue;
  if (reservedCloudflareExportNames.has(name)) {
    throw new Error('[flue] cloudflare.ts export "' + name + '" conflicts with a Flue-generated Worker export. Rename the authored export.');
  }
}
const cloudflareHandlers = 'default' in userCloudflare ? userCloudflare.default : {};
if (typeof cloudflareHandlers !== 'object' || cloudflareHandlers === null || Array.isArray(cloudflareHandlers)) {
  throw new Error('[flue] cloudflare.ts default export must be an object containing non-HTTP Worker handlers.');
}
if ('fetch' in cloudflareHandlers) {
  throw new Error('[flue] cloudflare.ts default export must not define fetch. Use app.ts for custom HTTP handling.');
}

// ─── Sandbox Environments ───────────────────────────────────────────────────

/**
 * Create an empty in-memory sandbox (default).
 */
async function createDefaultEnv() {
  const fs = new InMemoryFs();
  return bashFactoryToSessionEnv(() => new Bash({
    fs,
    network: { dangerouslyAllowFullInternetAccess: true },
  }));
}

const INTERNAL_DISPATCH_PATH = CLOUDFLARE_AGENT_INTERNAL_DISPATCH_PATH;
const INTERNAL_WORKFLOW_INVOKE_PATH = '/_flue/internal/workflow-invoke';
const dispatchQueue = {
  async enqueue(input) {
    const identity = agentIdentities[input.agent];
    const binding = env?.[identity?.bindingName];
    if (!binding) throw new Error('[flue] dispatch() target agent "' + input.agent + '" Durable Object binding is unavailable.');
    const response = await fetchAgent(binding, input.id, new Request('https://flue.invalid' + INTERNAL_DISPATCH_PATH, {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify(input),
    }));
    if (!response.ok) throw new Error('[flue] dispatch() target agent "' + input.agent + '" rejected durable admission with status ' + response.status + '.');
    return response.json();
  },
};

function createAgentContextForRequest({ executionStore, instance, agentName, request, initialEventIndex, dispatchId }) {
  return createFlueContext({
    id: instance.name,
    agentName,
    env: instance?.env ?? {},
    req: request,
    initialEventIndex,
    dispatchId,
    agentConfig: { resolveModel },
    createDefaultEnv,
    submissionStore: executionStore.submissions,
  });
}

function createWorkflowContextForRequest({ runId, request, initialEventIndex }, doInstance) {
  return createFlueContext({
    id: runId,
    runId,
    env: doInstance?.env ?? {},
    req: request,
    initialEventIndex,
    agentConfig: { resolveModel },
    createDefaultEnv,
  });
}

function createRunStoreForRequest(doInstance) {
  // Composite run store: per-workflow-DO records plus the FlueRegistry
  // index DO for cross-deployment lookup/listing.
  const sql = doInstance?.ctx?.storage?.sql;
  if (!sql) {
    throw new Error('[flue] Durable Object SQLite storage is unavailable — cannot create the run store. Flue Durable Object classes require SQLite-backed storage.');
  }
  return createCloudflareRunStore(createSqlRunStore(sql), doInstance?.env?.FLUE_REGISTRY);
}

// Falls back to the worker-level env so ambient callers (the listRuns()/
// getRun() primitives, which have no request scope) reach the index too.
function createRunIndexForRequest(reqEnv) {
  return createCloudflareRunIndex((reqEnv ?? env)?.FLUE_REGISTRY);
}

async function fetchAgent(binding, instanceId, request) {
  return (await getAgentByName(binding, instanceId)).fetch(request);
}

function runWithInstanceContext(doInstance, identity, fn) {
  return runWithCloudflareContext(
    {
      env: doInstance.env,
      storage: doInstance.ctx.storage,
      durableObjectIdentity: createDurableObjectIdentity(doInstance, identity),
    },
    fn,
  );
}

function createDurableObjectIdentity(doInstance, identity) {
  return {
    bindingName: identity.bindingName,
    className: identity.className,
    name: doInstance.name,
    id: doInstance.ctx.id.toString(),
  };
}

const eventStreamStores = new WeakMap();
const conversationStores = new WeakMap();

function createConversationStoresForInstance(doInstance) {
  const existing = conversationStores.get(doInstance);
  if (existing) return existing;
  const stores = createSqlConversationStores(doInstance?.ctx?.storage);
  conversationStores.set(doInstance, stores);
  return stores;
}

function createEventStreamStoreForInstance(doInstance) {
  const existing = eventStreamStores.get(doInstance);
  if (existing) return existing;
  const sql = doInstance?.ctx?.storage?.sql;
  if (!sql) {
    throw new Error('[flue] Durable Object SQLite storage is unavailable — cannot create the event stream store. Flue Durable Object classes require SQLite-backed storage.');
  }
  const store = new SqliteEventStreamStore(sql);
  eventStreamStores.set(doInstance, store);
  return store;
}

const devLifecycle = import.meta.env.DEV ? installDevLifecycleLogger() : undefined;
const cloudflareAgents = createCloudflareAgentRuntime({
  agents,
  createContext: createAgentContextForRequest,
  runWithInstanceContext: (instance, agentName, fn) => runWithInstanceContext(instance, agentRuntimeIdentity(agentName), fn),
  onInteractionStart: devLifecycle?.onAgentInteractionStart,
});

function assertAgentsDurabilityApi(doInstance, method) {
  if (typeof doInstance[method] !== 'function') {
		throw new Error(
			'[flue] The installed "agents" package does not provide the required Cloudflare Agents SDK method "' +
				method +
				'". Install or upgrade the "agents" package in your project.',
		);
	}
}

async function handleFlueWorkflowFiberRecovered(ctx, doInstance, workflowName) {
  if (!ctx.name || ctx.name !== 'flue:workflow:' + doInstance.name) return;
  const interruptedRunId = doInstance.name;
  const runStore = createRunStoreForRequest(doInstance);
  await failRecoveredRun({
    workflowName,
    runId: interruptedRunId,
    request: new Request('https://flue.invalid/workflows/' + encodeURIComponent(workflowName), { method: 'POST' }),
    error: new Error('Flue workflow execution was interrupted. Start a new workflow run explicitly if retry is appropriate.'),
    runStore,
    eventStreamStore: createEventStreamStoreForInstance(doInstance),
    createContext: (options) => createWorkflowContextForRequest(options, doInstance),
  });
}

async function dispatchWorkflow(request, doInstance, workflowName) {
  // The DO room name is the workflow instance id. For workflows that
  // equals the run id (one run per instance), so callers reach this DO
  // either by starting a new run (POST /workflows/:name → routed by the
  // outer worker) or by hitting a /runs/:runId subroute on an existing
  // instance.
  const instanceId = doInstance.name;
  const runRoute = parseRunRoute(request);
  if (runRoute) {
    // DS stream read (GET/HEAD on /runs/:runId) — use EventStreamStore.
    if (runRoute.action === 'ds-stream') {
      const store = createEventStreamStoreForInstance(doInstance);
      const streamPath = 'runs/' + runRoute.runId;
      if (request.method === 'HEAD') return await handleStreamHead(store, streamPath);
      return handleStreamRead({ store, path: streamPath, request });
    }
    return handleRunRouteRequest({
      workflowName,
      runId: instanceId,
      runStore: createRunStoreForRequest(doInstance),
    });
  }

  const workflow = workflows.find((record) => record.name === workflowName)?.definition;
  if (!workflow) return null;
  const identity = workflowRuntimeIdentity(workflowName);
  if (request.method === 'POST' && new URL(request.url).pathname === INTERNAL_WORKFLOW_INVOKE_PATH) {
    const { input } = await request.json();
    return runWithInstanceContext(doInstance, identity, async () => {
      const receipt = await admitDetachedWorkflow({
        workflowName,
        runId: instanceId,
        workflow,
        input,
        request,
        runStore: createRunStoreForRequest(doInstance),
        eventStreamStore: createEventStreamStoreForInstance(doInstance),
        createContext: (options) => createWorkflowContextForRequest(options, doInstance),
        startWorkflowAdmission: (runId, run) => {
          assertAgentsDurabilityApi(doInstance, 'runFiber');
          const admission = Promise.withResolvers();
          const completion = doInstance.runFiber('flue:workflow:' + runId, () => {
            admission.resolve();
            return runWithInstanceContext(doInstance, identity, run);
          });
          completion.catch(admission.reject);
          return { admitted: admission.promise, completion };
        },
      });
      return new Response(JSON.stringify(receipt), { status: 202, headers: { 'content-type': 'application/json' } });
    });
  }
  if (!parseWorkflowStart(request, workflowName)) return null;
  return runWithInstanceContext(doInstance, identity, () => handleWorkflowRequest({
      request,
      workflowName,
      runId: instanceId,
      workflow,
      runStore: createRunStoreForRequest(doInstance),
      eventStreamStore: createEventStreamStoreForInstance(doInstance),
      createContext: (options) => createWorkflowContextForRequest(options, doInstance),
      startWorkflowAdmission: (runId, run) => {
        assertAgentsDurabilityApi(doInstance, 'runFiber');
        const admission = Promise.withResolvers();
        const completion = doInstance.runFiber('flue:workflow:' + runId, () => {
          admission.resolve();
          return runWithInstanceContext(doInstance, identity, run);
        });
        completion.catch(admission.reject);
        return { admitted: admission.promise, completion };
      },
    }));
}



function workflowRuntimeIdentity(workflowName) {
  return workflowIdentities[workflowName];
}

function agentRuntimeIdentity(agentName) {
  return agentIdentities[agentName];
}

function parseWorkflowStart(request, workflowName) {
  if (request.method !== 'POST') return false;
  const url = new URL(request.url);
  const segments = url.pathname.split('/').filter(Boolean);
  if (segments.length < 2 || segments[segments.length - 2] !== 'workflows') return false;
  return decodeURIComponent(segments[segments.length - 1] || '') === workflowName;
}

function parseRunRoute(request) {
  const url = new URL(request.url);
  const segments = url.pathname.split('/').filter(Boolean);
  if (segments.length < 2 || segments[segments.length - 2] !== 'runs') return null;
  let runId;
  try {
    runId = decodeURIComponent(segments[segments.length - 1] || '');
  } catch {
    return null;
  }
  if (!runId) return null;
  // GET /runs/:runId?meta → run-record view; GET/HEAD otherwise → DS
  // stream read. The outer worker rejects other methods before
  // forwarding, so nothing else routes here.
  if (request.method === 'GET' && url.searchParams.has('meta')) return { action: 'get', runId };
  if (request.method === 'GET' || request.method === 'HEAD') return { action: 'ds-stream', runId };
  return null;
}

// ─── Per-Agent / Per-Workflow Durable Object Classes ──────────────────────


const workflowExtension0 = resolveCloudflareExtension(workflowModules["continue-market-intelligence-scan"], "continue-market-intelligence-scan", 'Workflow');
const FlueContinueMarketIntelligenceScanWorkflow = class FlueContinueMarketIntelligenceScanWorkflow extends workflowExtension0.base(Agent) {
  async onRequest(request) {
    return dispatchWorkflow(request, this, "continue-market-intelligence-scan");
  }

  async onFiberRecovered(ctx) {
    if (ctx.name?.startsWith('flue:workflow:')) {
      return handleFlueWorkflowFiberRecovered(ctx, this, "continue-market-intelligence-scan");
    }
    if (typeof super.onFiberRecovered === 'function') {
      return super.onFiberRecovered(ctx);
    }
  }
};
const WrappedFlueContinueMarketIntelligenceScanWorkflow = workflowExtension0.wrap(FlueContinueMarketIntelligenceScanWorkflow);
export { WrappedFlueContinueMarketIntelligenceScanWorkflow as FlueContinueMarketIntelligenceScanWorkflow };

const workflowExtension1 = resolveCloudflareExtension(workflowModules["market-intelligence-scan"], "market-intelligence-scan", 'Workflow');
const FlueMarketIntelligenceScanWorkflow = class FlueMarketIntelligenceScanWorkflow extends workflowExtension1.base(Agent) {
  async onRequest(request) {
    return dispatchWorkflow(request, this, "market-intelligence-scan");
  }

  async onFiberRecovered(ctx) {
    if (ctx.name?.startsWith('flue:workflow:')) {
      return handleFlueWorkflowFiberRecovered(ctx, this, "market-intelligence-scan");
    }
    if (typeof super.onFiberRecovered === 'function') {
      return super.onFiberRecovered(ctx);
    }
  }
};
const WrappedFlueMarketIntelligenceScanWorkflow = workflowExtension1.wrap(FlueMarketIntelligenceScanWorkflow);
export { WrappedFlueMarketIntelligenceScanWorkflow as FlueMarketIntelligenceScanWorkflow };

const workflowExtension2 = resolveCloudflareExtension(workflowModules["research-discovery-decision"], "research-discovery-decision", 'Workflow');
const FlueResearchDiscoveryDecisionWorkflow = class FlueResearchDiscoveryDecisionWorkflow extends workflowExtension2.base(Agent) {
  async onRequest(request) {
    return dispatchWorkflow(request, this, "research-discovery-decision");
  }

  async onFiberRecovered(ctx) {
    if (ctx.name?.startsWith('flue:workflow:')) {
      return handleFlueWorkflowFiberRecovered(ctx, this, "research-discovery-decision");
    }
    if (typeof super.onFiberRecovered === 'function') {
      return super.onFiberRecovered(ctx);
    }
  }
};
const WrappedFlueResearchDiscoveryDecisionWorkflow = workflowExtension2.wrap(FlueResearchDiscoveryDecisionWorkflow);
export { WrappedFlueResearchDiscoveryDecisionWorkflow as FlueResearchDiscoveryDecisionWorkflow };

const workflowExtension3 = resolveCloudflareExtension(workflowModules["research-discovery-finalization"], "research-discovery-finalization", 'Workflow');
const FlueResearchDiscoveryFinalizationWorkflow = class FlueResearchDiscoveryFinalizationWorkflow extends workflowExtension3.base(Agent) {
  async onRequest(request) {
    return dispatchWorkflow(request, this, "research-discovery-finalization");
  }

  async onFiberRecovered(ctx) {
    if (ctx.name?.startsWith('flue:workflow:')) {
      return handleFlueWorkflowFiberRecovered(ctx, this, "research-discovery-finalization");
    }
    if (typeof super.onFiberRecovered === 'function') {
      return super.onFiberRecovered(ctx);
    }
  }
};
const WrappedFlueResearchDiscoveryFinalizationWorkflow = workflowExtension3.wrap(FlueResearchDiscoveryFinalizationWorkflow);
export { WrappedFlueResearchDiscoveryFinalizationWorkflow as FlueResearchDiscoveryFinalizationWorkflow };

const workflowExtension4 = resolveCloudflareExtension(workflowModules["research-discovery-provider-action"], "research-discovery-provider-action", 'Workflow');
const FlueResearchDiscoveryProviderActionWorkflow = class FlueResearchDiscoveryProviderActionWorkflow extends workflowExtension4.base(Agent) {
  async onRequest(request) {
    return dispatchWorkflow(request, this, "research-discovery-provider-action");
  }

  async onFiberRecovered(ctx) {
    if (ctx.name?.startsWith('flue:workflow:')) {
      return handleFlueWorkflowFiberRecovered(ctx, this, "research-discovery-provider-action");
    }
    if (typeof super.onFiberRecovered === 'function') {
      return super.onFiberRecovered(ctx);
    }
  }
};
const WrappedFlueResearchDiscoveryProviderActionWorkflow = workflowExtension4.wrap(FlueResearchDiscoveryProviderActionWorkflow);
export { WrappedFlueResearchDiscoveryProviderActionWorkflow as FlueResearchDiscoveryProviderActionWorkflow };

const workflowExtension5 = resolveCloudflareExtension(workflowModules["translate"], "translate", 'Workflow');
const FlueTranslateWorkflow = class FlueTranslateWorkflow extends workflowExtension5.base(Agent) {
  async onRequest(request) {
    return dispatchWorkflow(request, this, "translate");
  }

  async onFiberRecovered(ctx) {
    if (ctx.name?.startsWith('flue:workflow:')) {
      return handleFlueWorkflowFiberRecovered(ctx, this, "translate");
    }
    if (typeof super.onFiberRecovered === 'function') {
      return super.onFiberRecovered(ctx);
    }
  }
};
const WrappedFlueTranslateWorkflow = workflowExtension5.wrap(FlueTranslateWorkflow);
export { WrappedFlueTranslateWorkflow as FlueTranslateWorkflow };

export { FlueRegistry };

// ─── Runtime seed ───────────────────────────────────────────────────────────

configureFlueRuntime({
  target: 'cloudflare',
  devMode: import.meta.env.DEV,
  temporaryLocalExposure: false,
  agents,
  workflows,
  dispatchQueue,
  admitWorkflow: async ({ workflowName, input }) => {
    const identity = workflowIdentities[workflowName];
    const binding = env?.[identity?.bindingName];
    if (!binding) throw new Error('[flue] invoke() target workflow Durable Object binding is unavailable.');
    const runId = generateWorkflowRunId();
    const response = await fetchAgent(binding, runId, new Request('https://flue.invalid' + INTERNAL_WORKFLOW_INVOKE_PATH, {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ input }),
    }));
    if (!response.ok) throw new Error('[flue] invoke() target workflow rejected durable admission with status ' + response.status + '.');
    return response.json();
  },
  channelHandlers,
  routeAgentRequest: async (request, reqEnv, target) => {
    const binding = reqEnv?.[agentIdentities[target.agentName]?.bindingName];
    if (!binding) return null;
    return fetchAgent(binding, target.instanceId, request);
  },
  routeWorkflowRequest: async (request, reqEnv, target) => {
    const binding = reqEnv?.[workflowIdentities[target.workflowName]?.bindingName];
    if (!binding) return null;
    return fetchAgent(binding, target.instanceId, request);
  },
  createRunIndexForRequest,
  routeRunRequest: async (request, reqEnv, target) => {
    // reqEnv is undefined for ambient callers (the getRun() primitive);
    // fall back to the worker-level env.
    const binding = (reqEnv ?? env)?.[workflowIdentities[target.workflowName]?.bindingName];
    if (!binding) return null;
    return fetchAgent(binding, target.runId, request);
  },
});

// ─── App composition ────────────────────────────────────────────────────────

// No app.ts: build the default app via @flue/runtime so the generated entry
// stays `hono`-free (users only need hono in their node_modules when
// they author their own app.ts). The default mounts `flue()` at root
// and renders canonical Flue envelopes for unmatched paths.
const flueApp = createDefaultFlueApp();

export default {
  ...cloudflareHandlers,
  fetch(request, env, ctx) {
    return flueApp.fetch(request, env, ctx);
  },
};
